### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by FoxyThePirateFoxx** [TriCkle-C/Sprinkle#2]
Funny how you say "Re-write" while you stole it. Prick.

**Comment by valid22** [comment]
Me, Stole it? Any proof, And This is my own scratch code!

**Comment by JakeyL** [comment]
Isnt it clear you steal from others always?

**Comment by valid22** [comment]
I just stole a Non-working , Only 1, Worst code from One site, After that I NEVER!

**Comment by JakeyL** [comment]
+ Thorn's buddy list :)

**Comment by valid22** [comment]
Buddy List, Stop. I wrote the whole SWF Part! BTW, CSS and JS are Obtainable

**Comment by JakeyL** [comment]
Don't act innocent, Little dote :)

**Comment by FoxyThePirateFoxx** [comment]
Please defend yourself, dont get others to defend yourself, Little dote.

**Comment by Elixur** [comment]
Are you seriously going to attack him with no proof? Dote is a lot smarter than you, ignorant prick. You assume he stole it because he stole something in the past, well news flash, he didn't steal python code, ever. Did you even BOTHER to look at his commits? He didn't dump this all at once and call it his own. He added code as he went along. You are so pathetic. Also CSS And JS used is from Club Penguin, it's not Thorn's own CSS and JS. Please defend yourself, little boy.

**Comment by iMix-** [comment]
Elixur, he copied the WHOLE SWF from Thorn, so don't try defending him, he's just a huge liar with non-existent abilities.

**Comment by Elixur** [comment]
Okay ignoring the swf, what about the source? lol

**Comment by iMix-** [comment]
I don't care about the source, but he didn't write it alone.

**Comment by Elixur** [comment]
I don't care about a swf, I care about the source lol. Everybody steals swfs, but don't attack him for stealing everything if he did write even 50% of this source. Everybody who writes their first source asks for help.

**Comment by valid22** [comment]
^^ Thanks for your support, BTW, I have all the proof of this Source written from Scratch!

**Comment by iMix-** [comment]
Show us it then?

**Comment by valid22** [comment]
This Rep. You aren't kidding, are u?

**Comment by JarRawr** [comment]
@Elixur Actually, my CSS and JS are all my own and not from Club Penguin. Also, not everyone steals swfs that other CPPS's made.

**Comment by valid22** [comment]
@https://github.com/JarRawr : You ever know, I left that behind, and started my Friends List, if not ask rile5

**Comment by JarRawr** [comment]
@valid22 You didn't "left that behind", you still used the code that I made as a base for your friends list. The CSS and HTML you gave me clearly shows that. Also, considering you've done nothing like this before I don't see how you were suddenly able to jump into a big project like a friends list with no experience without using other peoples stuff.

**Comment by valid22** [comment]
I DONT MIND LIERS

**Comment by iBetaEver** [comment]
[iMix]I don't care about the source, but he didn't write it alone.[/iMix]

Are you pretty sure? Because I am not. It's not that hard to put some packets and functions in the World.php in Kitsune lol (also some work with database). I can even do it.

@FoxyThePirateFoxx Hey, kid, weren't you crying on my Skype two months ago that everyone is flaming towards you like you do to dote and I had to return your self-confidence?
